---
- name: Generate Configuration 
  hosts:
    - all 
  roles: 
    - Juniper.junos 
  connection: local 
  gather_facts: no
  vars:
    tmp_dir: "ANS-CONFIG-GEN"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf" 

  tasks:
    - debug: var=tmp_dir
    
    - debug: var=conf_file
    
    - name: confirm or create config directory 
      file:
        path: "{{ tmp_dir }}"
        state: directory 

    - name: save device information using template 
      template: 
        src: /home/aahmed/template/base-settings.j2
        dest: "{{ conf_file }}"
