---
- name: Generate Configuration 
  hosts:
    - all 
  roles: 
    - Juniper.junos 
  connection: local 
  gather_facts: no
  vars:
    tmp_dir: "ANS-CONFIG-GEN"
    conf_file: "{{ tmp_dir }}/{{ inventory_hostname }}.conf" 

  vars_prompt:
  - name: username
    prompt: Junos Username
    private: no
  - name: password
    prompt: Junos Password
    private: yes        

  tasks:
    - debug: var=tmp_dir
    
    - debug: var=conf_file
    
    - name: confirm or create config directory 
      file:
        path: "{{ tmp_dir }}"
        state: directory 

    - name: save device information using template 
      template: 
        src: /home/aahmed/template/base-settings.j2
        dest: "{{ conf_file }}"

    - name: Install Configuration 
      junos_install_config:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        passwd: "{{ password }}"   
        file: "{{ conf_file }}"
        timeout: 120
        confirm: 10
        comment: "Playbook Deploy Configuration - Commit confirmed"
      notify: confirm commit

  handlers:
    - name: confirm commit
      junos_commit:
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        passwd: "{{ password }}"
        port: 22
        timeout: 120
        comment: "Playbook Generate install config - Confirming previous commit"
