---
- name: Get partial Config for Device 
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local 
  gather_facts: no
  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no
    - name: password
      prompt: Junos Password
      private: yes

  vars:
    partial_conf: "retrieve_partial_conf"
    conf_file_xml: "{{ partial_conf }}/{{ inventory_hostname }}.conf.xml"
    conf_file_text: "{{ partial_conf }}/{{ inventory_hostname }}.conf.txt"
    conf_file_json: "{{ partial_conf }}/{{ inventory_hostname }}.conf.json"
    connection_info:
      host: "{{ ansible_host }}"
      port: 22
      username: "{{ username }}"
      password: "{{ password }}"


  tasks:
    - name: create directory if needed for partial configuration
      file:
        path: "{{ partial_conf }}"
        state: directory

    - name: get device partial configuration
      junos_get_config:
        dest: "{{ conf_file_xml }}"
        provider: "{{ connection_info }}"
        format: "xml"
        filter: "system/login"

    - name: get device configuration
      junos_get_config:
        dest: "{{ conf_file_text }}"
        provider: "{{ connection_info }}"
        format: "text"
        filter: "system/login"

    - name: get device configuration
      junos_get_config:
        dest: "{{ conf_file_json }}"
        provider: "{{ connection_info }}"
        format: json
        filter: "system/login"

    - name: print version
      debug:
        var: junos.version 
